[bibliography]
== Literaturverweise

- [[[XOeV]]] +
  XÖV-Handbuch +
  http://www.bit.bund.de/cln_161/nn_1202296/BIT/DE/Shared/Publikationen/X_C3_96V-Handbuch__V1.0,templateId=raw,property=publicationFile.pdf/X%C3%96V-Handbuch_V1.pdf

- [[[X509]]] +
  Internet X.509 Public Key Infrastructure +
  http://tools.ietf.org/html/rfc3280

- [[[WSITools]]] +
  Test-Tool-Set für WS-I Konformität +
  http://www.ws-i.org/deliverables/workinggroup.aspx?wg=testingtools

- [[[WSI]]] +
  WS-I Basic Profile Version 1.0 +
  http://www.ws-i.org/Profiles/BasicProfile-1.0-2004-04-16.html

- [[[WindowBuilder]]] +
  WindowBuilder Pro Download-Seite +
  http://www.eclipse.org/windowbuilder/download.php

- [[[WikiJSF]]] +
  JavaServer Faces +
  http://de.wikipedia.org/wiki/JavaServer_Faces

- [[[WebStartMavenPlugin]]] +
  Webstart Maven Plugin +
  http://mojo.codehaus.org/webstart/webstart-maven-plugin/

- [[[Webservices]]] +
  Webservices in der IsyFact Anwendungslandschaft +
  20_Bausteine/Service-Gateway/Webservices_Anwendungslandschaft.pdf

- [[[WebGUIDetailkonzept]]] +
  Detailkonzept Komponente Web-GUI +
  10_Blaupausen/technische_Architektur/Detailkonzept_Komponente_Web_GUI.pdf

- [[[VorlageRegister]]] +
  Beispielimplementierung "Vorlage-Register" +
  Wird auf Anfrage bereitgestellt

- [[[VorlageGA]]] +
  Beispielimplementierung "Vorlage-Geschäftsanwendung" +
  Wird auf Anfrage bereitgestellt

- [[[UeberwachungKonfigKonzept]]] +
  Konzept Überwachung und Konfiguration +
  20_Bausteine\Ueberwachung_Konfiguration\Konzept_Ueberwachung-Konfiguration.pdf

- [[[TomahawkDataScroller]]] +
  Die Dokumentation der Tomahawk "DataScroller" Komponente +
  http://myfaces.apache.org/tomahawk-project/tomahawk20/tagdoc/t_dataScroller.html

- [[[Tomahawk]]] +
  Apache JSF Komponentenbibliothek +
  http://myfaces.apache.org/tomahawk/index.html

- [[[TemplatesDBSchemaVersionierung]]] +
  Templates für die Installation eines Datenbankschemas +
  10_Blaupausen\technische_Architektur\Templates-DB-Schema-Versionierung

- [[[SystemdokumentationMGW]]] +
  Systemdokumentation Mail-Gateway +
  20_Bausteine/Mail-Gateway/Systemdokumentation_Mail-Gateway.pdf

- [[[SWF]]] +
  Spring Web Flow Dokumentation +
  http://static.springsource.org/spring-webflow/docs/2.3.x/reference/html/

- [[[SUNRI]]] +
  SUN Referenzimplementierung JSF +
  http://java.sun.com/javaee/javaserverfaces/

- [[[Styleguide]]] +
  Styleguide +
  20_Bausteine\Styleguide\Styleguide.pdf

- [[[SSL]]] +
  Transport Layer Security +
  http://de.wikipedia.org/wiki/Transport_Layer_Security

- [[[SpringLDAPNutzungskonzept]]] +
  Nutzungskonzept Spring-LDAP +
  20_Bausteine\LDAP-Zugriffe\Nutzungskonzept_Spring_LDAP.pdf

- [[[SpringLDAP]]] +
  Spring LDAP +
  http://www.springframework.org/ldap (Zugriff am 10.12.2014)

- [[[Spring]]] +
  Spring Framework Reference Documentation +
  http://docs.spring.io/spring-framework/docs/3.1.x/spring-framework-reference/html/

- [[[Spooling]]] +
  Konzept Spooling +
  20_Bausteine\Spooling\Konzept_Spooling.pdf

- [[[SicherheitNutzerdok]]] +
  Nutzerdokumentation Sicherheit +
  20_Bausteine\Sicherheitskomponente\Nutzerdokumentation_Sicherheit.pdf

- [[[ServicekommunikationKonzept]]] +
  Grundlagen der Servicekommunikation innerhalb der Plattform +
  10_Blaupausen\Integrationsplattform\Grundlagen_interne_Servicekommunikation.pdf

- [[[ServiceGatewaySystementwurf]]] +
  Systemdokumentation Service-Gateway +
  20_Bausteine/Service-Gateway/Systemdokumentation_Service-Gateway.pdf

- [[[ServiceDetailkonzept]]] +
  Detailkonzept Komponente Service +
  10_Blaupausen\technische_Architektur\Detailkonzept_Komponente_Service.pdf

- [[[RPM]]] +
  RPM Guide +
  http://docs.fedoraproject.org/drafts/rpm-guide-en/

- [[[RegelwerkKonzept]]] +
  Konzept Regelwerk +
  20_Bausteine\Regelwerk\Konzept_Regelwerk.pdf

- [[[RegelwerkDroolsDok]]] +
  Drools Documentation +
  http://www.jboss.org/drools/documentation

- [[[QuasarClient]]] +
  Quasar Client Dokumentation +
  10_Blaupausen/technische_Architektur/Quasar_Client

- [[[ProtokollierungKonzept]]] +
  Konzept Protokollierung +
  20_Bausteine\Protokollierung_Protokollrecherche\Konzept_Protokollierung.pdf

- [[[PollingNutzerDok]]] +
  Konzept Protokollierung +
  20_Bausteine\Polling\Nutzerdokumentation_Polling.pdf

- [[[Programmierkonventionen]]] +
  Polling Nutzerdokumentation +
  40_Methodik\30_Implementierung\Java-Programmierkonventionen.pdf

- [[[ProduktKatalog]]] +
  IsyFact Produktkatalog +
  00_Allgemein\Produktkatalog.pdf

- [[[PortalKonzept]]] +
  Konzept Portal +
  20_Bausteine/Portal/Konzept_Portal.pdf

- [[[IsyFactReferenzarchitekturITSystem]]] +
  IsyFact – Referenzarchitektur für IT-Systeme +
  00_Allgemein\IsyFact_Referenzarchitektur-IT-System.pdf

- [[[IsyFactJQuery]]] +
  Paketierte JQuery-Dateien für IsyFact-Anwendungen +
  60_Software\Bibliotheken\web-gui

- [[[IsyFactTutorial]]] +
  IsyFact – Tutorial +
  00_Allgemein\IsyFact-Tutorial.pdf

- [[[IsyFactSystementwurf]]] +
  Vorlage für Systementwürfe +
  40_Methodik\20_Systementwurf\IsyFact-Vorlage_Systementwurf.dot

- [[[IsyFactVorlageSystemhandbuch]]] +
  Vorlage Systemhandbuch +
  40_Methodik\30_Implementierung\IsyFact-Vorlage_Systemhandbuch.dotx

- [[[IsyFactEinstieg]]] +
  IsyFact-Einstieg +
  00_Allgemein\IsyFact-Einstieg.pdf

- [[[TailoringVorlage]]] +
  Vorlage für IsyFact Tailoring Dokument +
  00_Allgemein\IsyFact-Tailoring.dotx

- [[[PKCS12]]] +
  PKCS #12: Personal Information Exchange Syntax Standard +
  http://www.rsa.com/rsalabs/node.asp?id=2138

- [[[PatternLayout]]] +
  JavaDoc Dokumentation zum Patternlayout Version 1.2 +
  http://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/PatternLayout.html

- [[[OWASP10]]] +
  OWASP Top 10 Project +
  https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project

- [[[OSCI2]]] +
  OSCI-Transport, Version 2.0 Web Services Profiling and Extensions Specification Edition 3 +
  http://www.osci.eu/transport/osci20/20100427/OSCI20_WS-ProfilingAndExtensionSpecification_Edition3.pdf

- [[[NutzungskonzeptErstellungSGW]]] +
  Nutzungskonzept Service-Gateway-Erstellung +
  20_Bausteine/Service-Gateway/Nutzungskonzept_Service-Gateway_Erstellung.pdf

- [[[Nutzungskonzept_jBPM]]] +
  Nutzungskonzept jBPM +
  20_Bausteine\Workflow\Nutzungskonzept_jBPM.pdf

- [[[NutzerDokumentationSGW]]] +
  Nutzerdokumentation Service-Gateway +
  20_Bausteine/Service-Gateway/Nutzerdokumentation_Service-Gateway.doc

- [[[NativeGUIDetailkonzept]]] +
  Detailkonzept Komponente Native-GUI +
  10_Blaupausen\technische_Architektur\Detailkonzept_Komponente_Native_GUI.pdf

- [[[Namenskonventionen]]] +
  IsyFact – Namenskonventionen +
  00_Allgemein\IsyFact-Namenskonventionen.pdf

- [[[ModelViewPresenter]]] +
  GUI Architectures +
  http://www.martinfowler.com/eaaDev/uiArchs.html

- [[[MiGLayout]]] +
  MigLayout - Java Layout Manager +
  http://www.miglayout.com/

- [[[Metro]]] +
  Die Metro Webservice-Bibliothek +
  https://metro.dev.java.net/

- [[[LSB]]] +
  Linux Standard Base +
  http://www.linuxbase.org/

- [[[LoggingKonzept]]] +
  Konzept Logging +
  20_Bausteine\Logging\Konzept_Logging.pdf

- [[[Log4jPerformance]]] +
  log4j Manual - Kapitel Performance +
  http://logging.apache.org/log4j/1.2/manual.html#performance

- [[[KonzeptSchnittstellenSGW]]] +
  Konzept Service-Gateway-Schnittstellen +
  20_Bausteine/Service-Gateway/Konzept_Service-Gateway_Schnittstellen.pdf

- [[[KMHandbuch]]] +
  Konfigurations-Management-Handbuch (INTERN) +


- [[[JSSE]]] +
  JavaTM Secure Socket Extension (JSSE) Reference Guide for the JavaTM 2 Platform Standard Edition 5 +
  http://java.sun.com/j2se/1.5.0/docs/guide/security/jsse/JSSERefGuide.html

- [[[JPA]]] +
  Java Persistence API +
  http://java.sun.com/javaee/overview/faq/persistence.jsp

- [[[JMXPatterns]]] +
  Design patterns for JMX and application manageability - A guide for Developers +
  http://devresource.hp.com/drc/resources/jmxds/index.jsp

- [[[JMXParam]]] +
  Monitoring and Management Using JMX +
  http://java.sun.com/j2se/1.5.0/docs/guide/management/agent.html

- [[[JMXBestPrac]]] +
  Java Management Extensions (JMX) - Best Practices +
  http://java.sun.com/javase/technologies/core/mntr-mgmt/javamanagement/best-practices.jsp

- [[[JFormDesigner]]] +
  JFormDesigner Homepage +
  http://www.formdev.com/

- [[[jBPMHomepage]]] +
  jBPM Homepage +
  http://www.jboss.com/products/jbpm/

- [[[ITGS06]]] +
  IT-Grundschutzkatalog, Baustein B 1.12, Stand 2006 +
  https://www.bsi.bund.de/DE/Themen/ITGrundschutz/itgrundschutz_node.html

- [[[HibernateVererbung]]] +
  Hibernate: Implementierung von Vererbung +
  http://www.hibernate.org/hib_docs/v3/reference/en/html/inheritance.html

- [[[GroupLayout]]] +
  How to Use GroupLayout +
  http://download.oracle.com/javase/tutorial/uiswing/layout/group.html

- [[[FormLayout]]] +
  JGoodies FormLayout +
  http://www.jgoodies.com/freeware/libraries/forms/

- [[[FHS]]] +
  Filesystem Hierarchy Standard +
  http://www.pathname.com/fhs/

- [[[FehlerbehandlungKonzept]]] +
  Konzept Fehlerbehandlung +
  20_Bausteine\Fehlerbehandlung\Konzept_Fehlerbehandlung.pdf

- [[[FachlicheArchitektur]]] +
  Darstellung d. fachlichen Architektur (INTERN) +

- [[[Facelets]]] +
  Facelets +
  https://facelets.dev.java.net/

- [[[IsyFactJQuery]]]] +
  Paketierte JQuery-Dateien für IsyFact-Anwendungen +
  60_Software\Bibliotheken\web-gui.

- [[[Dozer]]] +
  Die Dozer Bibliothek +
  http://dozer.sourceforge.net/

- [[[DeploymentKonzept]]] +
  Konzept Deployment für IsyFact-Anwendungen +
  30_Plattform\Konzept_Deployment.pdf

- [[[Deme05]]] +
  Zeitmaschine – Temporale Datenhaltung +
  http://www.sigs-datacom.de/fileadmin/user_upload/zeitschriften/js/2003/05/demelt_JS_05_03.pdf

- [[[DatenzugriffDetailkonzept]]] +
  Detailkonzept Komponente Datenzugriff +
  10_Blaupausen\technische_Architektur\Detailkonzept_Komponente_Datenzugriff.pdf

- [[[CommonEL]]] +
  Common Expression Language +
  http://commons.apache.org/el/

- [[[Berechtigungskonzept]]] +
  Berechtigungskonzept +
  Muss projektspezifisch erstellt werden

- [[[BatchDetailkonzept]]] +
  Detailkonzept Komponente Batch +
  10_Blaupausen/technische_Architektur/Detailkonzept_Komponente_Batch.pdf

- [[[ApacheTomcatKonzept]]] +
  Konzept Apache Tomcat (INTERN) +

- [[[Collections]]] +
  Hiberate Documentation: Chapter 6. Collection Mapping +
  http://www.hibernate.org/hib_docs/v3/reference/en/html/collections.html (Zugriff am 10.12.2014)

- [[[Components]]] +
  Hiberate Implementierung von 1:n Assoziationen +
  http://www.hibernate.org/hib_docs/v3/reference/en/html/collections.html (Zugriff am 10.12.2014)

- [[[AnwendungskernDetailkonzept]]] +
  Detailkonzept der Komponente Anwendungskern +
  10_Blaupausen\technische_Architektur\Detailkonzept_Komponente_Anwendungskern.pdf

- [[[Batch]]] +
  Batch-Verarbeitung mit Hibernate +
  http://www.hibernate.org/hib_docs/v3/reference/en/html/batch.html (Zugriff am 10.12.2014)

- [[[WindowBuilderEclipse]]] +
  Windows Builder Becomes New Open Source Project +
  http://googlecode.blogspot.com/2010/12/windowbuilder-becomes-new-open-source.html

- [[[BaKi07]]] +
  Christian Bauer, Gavin King. Java Persistence with Hibernate. 2007. Manning Publications

- [[[Quasar]]] +
  Johannes Siedersleben. Moderne Softwarearchitektur - Umsichtig planen, robust bauen mit Quasar. 2004. d.punkt.verlag

- [[[iXGuiBuilder]]] +
  Bernhard Steppan. Polierte Oberflächen: Eclipse-GUI-Builder für Swing- und SWT-Rich-Clients +
  iX 2 2009 S. 88-92

- [[[IsyFactSystemspezifikation]]] +
  Vorlage für Systemspezifikationen +
  40_Methodik\20_Systementwurf\IsyFact-Vorlage_Systemspezifikation.dot

- [[[IsyFactVorlageAnforderungsliste]]] +
  Vorlage für Anforderungsliste +
  40_Methodik\10_Systemspezifikation\IsyFact-Vorlage-Anforderungsliste.xlsx

- [[[AnleitungDatenflussdiagramme]]] +
  Anleitung zur Erstellung und zum Lesen von Datenflussdiagrammen +
  40_Methodik\10_Systemspezifikation\Anleitung_zu_Datenflussdiagrammen.dotx

- [[[IsyFactReferenzarchitektur]]] +
  IsyFact – Referenzarchitektur +
  00_Allgemein\IsyFact-Referenzarchitektur.pdf

- [[[DGSG]]] +
  Oracle: Globalization Support Guide 10g Release 2 (10.2) +
  http://download.oracle.com/docs/cd/B19306_01/server.102/b14225.pdf

- [[[SonderzeichenKonzept]]] +
  Transkriptions-Regeln +
  20_Bausteine\Sonderzeichen\Konzept_Umgang_mit_Sonderzeichen.pdf

- [[[Transskriptionsregeln]]] +
  Transkriptions-Regeln +
  20_Bausteine\Sonderzeichen\Transkriptionsregeln.xls

- [[[XOEVStringLatin]]] +
  Handbuch zur Entwicklung XÖV-konformer IT-Standards (Anhang A) +
  http://www.xoev.de/sixcms/media.php/13/2010-03-02-Handbuch-final.pdf (Zugriff am 11.12.2014)

- [[[SLMapping]]] +
  Mapping-Tabelle für die Transformation von String.Latin-Zeichen +
  20_Bausteine\Sonderzeichen\Mappingtabelle.xls

- [[[SAGA40]]] +
  SAGA Version 4.0 – Standards und Architekturen für E-Government-Anwendungen; Publikation der KBSt; +
  http://www.kbst.bund.de/saga

- [[[Sun1997]]] +
  Java Code Conventions. +
  http://java.sun.com/docs/codeconv/

- [[[Ambler1999]]] +
  Writing Robust Java Code. The AmbySoft Inc. Coding Standards for Java v17.01d +
  http://www.ambysoft.com/downloads/javaCodingStandards.pdf

- [[[Vermeulen2000]]] +
  Allan Vermeulen, Scott W. Ambler, Greg Baumgardner, Eldon Metz, Trevor Misfeldt, Jim Shur, Patrick Thomson. The Elements of Java Style. 2000. Cambridge University

- [[[NutzungsvorgabenLogging]]] +
  Nutzungsvorgaben Logging +
  20_Bausteine\Logging\Nutzungsvorgaben_Logging.pdf

- [[[NutzungsvorgabenLogserver]]] +
  Nutzungsvorgaben Logserver +
  Link wird ergänzt, wenn Dokument fertiggestellt wurde

- [[[NutzungskonzeptHTTPServer]]] +
  Nutzungskonzept HTTP Server +
  30_Plattform/Nutzungskonzept_Apache_HTTP_Server.pdf

- [[[NutzungskonzeptIsyUtil]]] +
  Nutzungskonzept Isy-Util +
  20_Bausteine\Util\Nutzungskonzept_isy-util.pdf

- [[[KonzeptDatumZeit]]] +
  Konzept Datum & Zeit +
  20_Bausteine\Datum_Zeit\Konzept_Datum_Zeit.pdf

- [[[NutzungsvorgabenDatumZeit]]] +
  Nutzungsvorgaben Datum & Zeit +
  20_Bausteine\Datum_Zeit\Nutzungsvorgaben_Datum_Zeit.pdf

- [[[KonzeptTaskScheduling]]] +
  Konzept Task Scheduling +
  20_Bausteine\Task_Scheduling\Konzept_Task_Scheduling.pdf

- [[[NutzungsvorgabenTaskScheduling]]] +
  Nutzungsvorgaben Task Scheduling +
  20_Bausteine\Task_Scheduling\Nutzungsvorgaben_Task_Scheduling.pdf

- [[[Vorlageanwendung]]] +
  IsyFact-Vorlageanwendung "Terminfindung" +
  https://github.com/IsyFact/IsyFact-Vorlageanwendung

- [[[NutzungskonzeptRedis]]] +
  Nutzungskonzept Redis +
  30_Plattform\Nutzungskonzept_Redis.pdf

- [[[NutzungskonzeptIsySession]]] +
  Nutzungskonzept Isy-Session +
  20_Bausteine\Session-Management\Nutzungskonzept_Isy-Session.pdf

- [[[KonzeptSessionManagement]]] +
  Konzept Session Management +
  20_Bausteine\Session-Management\Konzept_Session_Management.pdf

- [[[TomcatNutzungskonzept]]] +
  Nutzungskonzept Apache Tomcat +
  30_Plattform\Nutzungskonzept_Apache_Tomcat_8.pdf

- [[[Versionierung]]] +
  IsyFact - Versionierung +
  00_Allgemein/IsyFact-Versionierung.pdf

- [[[KonzeptLoggingInfrastrukturELK]]] +
  Konzept Logging Infrastruktur ELK +
  30_Plattform\Konzept_Logging-Infrastruktur_ELK.pdf

- [[[Ucp15]]] +
  Universal Connection Pool for JDBC Developer's Guide +
  https://docs.oracle.com/cd/E11882_01/java.112/e12265/optimize.htm (Zugriff am 13.08.2015)

- [[[SemanticVersioning]]] +
  Semantic Versioning 2.0.0 +
  http://semver.org/spec/v2.0.0.html [Zugriff am 05.03.2018]

- [[[SystemdokumentationServiceGateway]]] +
  Systemdokumentation Service-Gateway +
  20_Bausteine/Service-Gateway/Systemdokumentation_Service-Gateway.pdf

- [[[Einrichtung_Entwicklungsumgebung]]] +
  Einrichtung einer Entwicklungsumgebung – Boilerplate Code und Formatierung +
  50_Werkzeuge/Einrichtung_Entwicklungsumgebung.pdf

- [[[Leitfaden-Entwicklungsumgebung]]] +
  Leitfaden zur Einrichtung der Entwicklungsumgebung +
  50_Werkzeuge/Leitfaden-Entwicklungsumgebung.pdf

- [[[NutzungsvorgabenBenutzerverwaltung]]] +
  Nutzungsvorgaben Benutzerverwaltung +
  20_Bausteine\Benutzerverwaltung\Nutzungsvorgaben_IsyFact-Benutzerverwaltung.pdf

- [[[jenerate]]] +
  jenerate - Java Generation Plugin for Eclipse +
  https://github.com/maximeAudrain/jenerate

- [[[Bloch2008]]]
  J. Bloch. Effective Java Second Edition. 2008. Addison Wesley.
